[package]
name = "nl80211-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nl80211-ng = { version = "0.2.4", path = "../nl80211-ng"}
rand = "0.8.5"
